#!/usr/bin/env python3
"""Check the demo board's fixture table against the firmware's own source.

`apps/configurator/src/firmware/demo-table.json` is the demo board's starting
state: the rows `DemoBoard` is handed at boot, which it then serves back over
`param info` and `param help`. It is generated by `tools/capture-fixtures.py` and
it must stay the firmware's table, or the demo board starts drifting away from
the thing it is a model of.

It was `parameter-table.json` until 2026-09-30, and until then it was not a
fixture at all — it was the app's *only* source of ranges, decimal places, help
text and groups, shown beside whatever board answered. It had been a 32-row
snapshot of a 33-row table, missing `arm_accel_lpf_hz`, and every consumer joined
it to the board's reply on `name`: a name the file lacked produced a row with no
range, which looks exactly like a parameter that has none. Nothing failed for a
whole release.

The app no longer reads this file at all — a board's description arrives over
`param info` or it does not arrive — so this check is now about the *fixture*
rather than about a lie the app tells. It is kept, and kept strict, because the
demo board is the peer the app's whole metadata path is tested against, and a
fixture that has quietly drifted tests the wrong thing.

It compares the stored rows against `ak_table.py`'s extraction of `ak_flight.c`,
index by index, and fails on:

  - a name that differs at an index both sides have,
  - a group that differs at an index both sides have,
  - a row the firmware has and the file does not,
  - a row the file has and the firmware does not,
  - a file row whose index is not its position in the file.

Strictness including for missing rows is the point. A check that only compared
the rows both sides happen to have would have passed on the day
`arm_accel_lpf_hz` was added, which is exactly how the off-by-one shipped.

Usage:
    python3 tools/check-table-drift.py [--repo-root DIR]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent


def find_root() -> Path | None:
    for parent in Path(__file__).resolve().parents:
        if (parent / "aerialkit" / "src").is_dir():
            return parent
    return None


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--repo-root", default=None)
    args = parser.parse_args(argv)

    root = Path(args.repo_root).resolve() if args.repo_root else find_root()
    if root is None:
        print("check-table-drift: no repository root found")
        return 1

    sys.path.insert(0, str(HERE))
    import ak_table  # noqa: E402

    stored_path = root / "apps" / "configurator" / "src" / "firmware" / "demo-table.json"
    stored = json.loads(stored_path.read_text())["parameters"]

    try:
        firmware = ak_table.extract(
            root / "aerialkit" / "src" / "core" / "flight" / "ak_flight.c",
            root / "aerialkit" / "src",
        )
    except ak_table.TableError as error:
        print(f"check-table-drift: could not read the firmware's table: {error}")
        return 1

    problems: list[str] = []
    for position, row in enumerate(stored):
        if row.get("index") != position:
            problems.append(
                f"row {position} carries index {row.get('index')}; the file's own "
                "order and its indices disagree"
            )

    for index in range(min(len(stored), len(firmware))):
        if stored[index]["name"] != firmware[index]["name"]:
            problems.append(
                f"index {index}: the file says {stored[index]['name']!r}, "
                f"ak_flight.c declares {firmware[index]['name']!r}"
            )
        # The group is the last argument of every registration, which is what
        # makes a forgotten one a compile error there. Here it is the number the
        # demo board serves and the app renders under a name it carries itself,
        # so a fixture whose groups had drifted would have the demo board filing
        # parameters under the wrong heading — and the tab the app draws from it
        # would be wrong in a way no other test could see.
        elif stored[index].get("group") != firmware[index].get("group"):
            problems.append(
                f"index {index} ({stored[index]['name']!r}): the file says group "
                f"{stored[index].get('group')}, ak_flight.c registers it in group "
                f"{firmware[index].get('group')}"
            )

    missing = [row["name"] for row in firmware[len(stored) :]]
    extra = [row["name"] for row in stored[len(firmware) :]]
    for name in missing:
        problems.append(f"ak_flight.c declares {name!r}; the file has no row for it")
    for name in extra:
        problems.append(f"the file has a row for {name!r}; ak_flight.c does not declare it")

    if problems:
        print(
            f"check-table-drift: the fixture disagrees with ak_flight.c — "
            f"{len(stored)} row(s) stored, {len(firmware)} declared there"
        )
        # Said out loud because the line above was read as the *board's* count
        # by the person who wrote it. ak_flight.c is the flight table; the board
        # registers the rest in main.c, and the gap against a real board is far
        # larger than the one this script can see. 92 is measured, not
        # estimated: `python3 aerialkit/tools/akproto_firmware_check.py` prints
        # "and says how many parameters it has 92 parameters" against
        # `aerialkit-fw-sim 0 console`, 2026-09-30.
        #
        # The gap is deliberate here in a way it was not before: the demo board
        # is a model of the *flight* table, and the ~59 rows main.c registers
        # (network, logging, timing and the rest) are not part of it. What is
        # not allowed is the *fixture* disagreeing with the 33 that are.
        print(
            "  scope: ak_flight.c is the flight table only. The board registers "
            "more in src/core/main.c,\n"
            "         which this script cannot read, so the real gap is wider: "
            "the firmware reports 92\n"
            "         parameters over `hello`, against this fixture's "
            f"{len(stored)}. That is by design —\n"
            "         the demo board models the flight table — but the rows it "
            "does carry must match."
        )
        for problem in problems[:20]:
            print(f"  {problem}")
        if len(problems) > 20:
            print(f"  ... and {len(problems) - 20} more")
        return 1

    print(
        f"check-table-drift: {len(stored)} row(s) agree with ak_flight.c, "
        "name and group, index by index"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
